### ISSUE TITLE
Security issues with the version of lodash being used

### ISSUE THREAD

**Issue by jwblangley** [volumenetwork/video-thumbnail-generator#10]
I'm using your tool in my project and github has flagged up to me some security issues with the version of lodash that is a dependency of this tool. I have attached the security report as well as the version of lodash that this tool is using.

Please update the version of lodash in this project to the more recent version. 
Thank you
![lodash-security](https://user-images.githubusercontent.com/14108795/65139516-b2713a00-da04-11e9-81d7-114b4b544087.png)
![lodash-security-2](https://user-images.githubusercontent.com/14108795/65139518-b2713a00-da04-11e9-97fe-03565f7bbe74.png)

**Comment by gritex** [comment]
I agree. Please update the Lodash version.

**Comment by jrohland** [comment]
I ran into the same issue. Forked and fixed with PR #12 .
