### ISSUE TITLE
Docs: (err, result) are switched

### ISSUE THREAD

**Issue by ferares** [volumenetwork/video-thumbnail-generator#3]
It seems the (err, result) parameters are switched in the documentation compared to what actually happens in the code, the correct order is (result, err).

Also could you clarify what does "generateOneByPercent" do?

Thanks.

**Comment by irvingswiftj** [comment]
Hi ferares,

I'm just looking at the code, and all the functions that take callbacks do expect the callbacks to be (err, result) => {}. Could you please let me know which function in particular you are referring to?

Futher to this, I would advise using the Functions that return promises over the ones that take callbacks. They are only there for legacy reasons.

GenerateOnByPercent is a function to generate a thumbnail for a certain part of the video. i.e. if you specified 10%, the thumbnail would be from 10% the way through the video.

I hope this helps.

**Comment by ferares** [comment]
Hi, thanks for the quick response, this is the call I'm using:

```
generateOneByPercent(50).then((err, res) => {
  console.log('res', res);
  console.log('err', err);
});
```

If I do it like this then the response is in the err variable and null is in the res one.

Thanks for the clarification on the generateOneByPercent function.

**Comment by irvingswiftj** [comment]
Ah, I see the problem. It seems you are using the functions that return Promises but with functions that are error first callbacks.

There are two options here:

1) Use promises:
```
generateOneByPercent(50, { size: '300x300' })
  .then((res) => {
    console.log('res', res);
  })
  .catch((err) => {
      console.log('err', err);
  });
```
(If still unsure, I recommend reading https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)

2) Use the callback method:
```
generateOneByPercentCb(50, { size: '300x300' }, (err, res) => {
  console.log('res', res);
  console.log('err', err);
});
```

I hope this helps
