### ISSUE TITLE
Readme mistake and dependencies need updating

### ISSUE THREAD

**Issue by Angelk90** [volumenetwork/video-thumbnail-generator#4]
@irvingswiftj : First of all, I wanted to congratulate you on the module, even if you still could not try it for different problems.

1) In the readme.md file, it is written that the module name is:
import ThumbnailGenerator from 'volume-thumbnail-generator';
In reality it should be:
import ThumbnailGenerator from 'video-thumbnail-generator';

2) We could update the version of the dependencies, in particular of:
-del
-fluent-ffmpeg

P.Š.
Tells me:
unable to resolve module 'path' from '... \ node_modules \ del \ index.js': Module does not exist in the module map.

The module is there but I do not understand how to solve everything, some advice?

**Comment by irvingswiftj** [comment]
Hi,

On point 1, yes you are right, i will fix that straight away.
Point 2, I should update the deps, i will do when i get a chance.

Your error:
`unable to resolve module 'path' from '... \ node_modules \ del \ index.js': Module does not exist in the module map.`

What version of node.js are you using?

**Comment by Angelk90** [comment]
v6.10.2

**Comment by irvingswiftj** [comment]
odd, it is building on node 6  (6.12.2) for me. I will investigate

**Comment by Angelk90** [comment]
You could do this test, create a new project all over again and install your module if it gives you problems.

P.Š.
A question, if the video is on http, is it possible to use it or not your module?

**Comment by irvingswiftj** [comment]
I have never tried over http, off the top of my head i would have thought not. Feel free to add it as a feature request.

**Comment by Angelk90** [comment]
@irvingswiftj : So it only works locally? I had asked about a group of facebook, I had recommended the following form. But in the readme, there was nothing in which it indicated that it only worked locally, the only thing that made me doubt was the sourcePath that was understood to be going local.

I needed to work on http, do not you know some module that does it?

**Comment by irvingswiftj** [comment]
i'm afraid i don't, but you could download the video to a tmp directory, generate the thumbnail(s) and then delete the downloaded video.

**Comment by Angelk90** [comment]
@irvingswiftj : 
Let's talk about videos of different Gigabytes, I think it's not possible. :(

**Comment by irvingswiftj** [comment]
a quick google led me to this https://www.npmjs.com/package/video-thumbnail-extractor.

It might be more aligned to what you are after.

**Comment by Angelk90** [comment]
@irvingswiftj : I tried too but I could not find anything.
What you tell me, works on microservice I do not think you can use in my case.

Anyway, let me know if you can solve the problem 2, you never know I could serve you. ;)

P.Š.
How do you make the request a feature request, you did not happen to me, I have no idea how to do it.
You never know, I'll do it.
