### ISSUE TITLE
is this only for mp4 files ?

### ISSUE THREAD

**Issue by siberfx** [volumenetwork/video-thumbnail-generator#7]
for example I need to find a package which is taking thumbnails from "mp4, ogg, webm" files, are we able to do it for these formats too ?

**Comment by irvingswiftj** [comment]
I have only tested with mp4. I should test what other files it works with.

**Comment by siberfx** [comment]
I already did. Webm, og4 and so on. It works.

Selim GORMUS - Asus zenfone 2
